* scratch-pop.el

"scratch"バッファをポップアップ

pop-up "scratch"es

** USER-VISIBLE CHANGES IN THE LAST VERSION

- now auto-yank feature is disabled by default. to enable the feature,
  set `scratch-pop-enable-auto-yank' non-nil.

  : (setq scratch-pop-enable-auto-yank t)

** Usage

Load this script

: (require 'scratch-pop)

and you can popup a scratch buffer with "M-x scratch-pop". If a
scratch is already displayed, then another one is created. You may
also bind some keys to "scratch-pop" if you want.

: (global-set-key "C-M-s" 'scratch-pop)

You can backup scratches by calling `scratch-pop-backup-scratches'
after setting `scratch-pop-backup-directory', and then restore
backups by calling `scratch-pop-restore-scratches'.

: (setq scratch-pop-backup-directory "~/.emacs.d/scratch_pop/")
: (scratch-pop-backup-directory)
: (scratch-pop-restore-scratches)

It's good idea to put `scratch-pop-backup-directory' into
`kill-emacs-hook' so that scratches are automatically saved when
killing emacs.

: (add-hook 'kill-emacs-hook 'scratch-pop-backup-scratches)
